using Content.Client.UserInterface.Controls;
using Content.Shared.AWS.Economy;
using Content.Client.AWS.Economy.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Linq;

namespace Content.Client.AWS.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class EconomyLogConsoleMenu : FancyWindow
{
    [Dependency] private readonly IEntitySystemManager _entitySystem = default!;
    private EconomyLogConsoleBoundUserInterface Owner { get; set; }
    private Dictionary<string, EconomyBankAccountComponent> _accounts;
    public EconomyLogConsoleMenu(EconomyLogConsoleBoundUserInterface owner)
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        var economyBankAccount = _entitySystem.GetEntitySystem<EconomyBankAccountSystemShared>();

        LogDetails.SelectMode = ItemList.ItemListSelectMode.None;

        Owner = owner;
        _accounts = economyBankAccount.GetAccounts();

        FillList();

        FindAccount.OnTextEntered += OnTextEnteredAccount;
        FindLog.OnTextEntered += OnTextEnteredLog;

    }

    private void OnSelectAccount(ItemList.Item accountId)
    {
        LogDetails.Clear();


        for (int i = _accounts[accountId.Text!].Logs.Count - 1; i != -1; i--)
        {
            var item = _accounts[accountId.Text!].Logs[i];
            LogDetails.AddItem("[" + item.Date.ToString("hh\\:mm\\:ss") + "] — " + item.Text);
        }
    }

    private void OnTextEnteredAccount(LineEdit.LineEditEventArgs eventArgs)
    {
        AccountList.Clear();
        var upText = eventArgs.Text.ToUpper();
        foreach (var (key, value) in _accounts)
        {
            if (key.Contains(upText))
            {
                var field = AccountList.AddItem(key);
                field.OnSelected += OnSelectAccount;
            }
        }
        AccountList.SortItemsByText();
    }
    private void OnTextEnteredLog(LineEdit.LineEditEventArgs eventArgs)
    {

        if (!AccountList.GetSelected().Any())
        {
            LogDetails.Clear();
            LogDetails.AddItem("Error no select Account");
            return;
        }
        var accountId = AccountList.GetSelected().First();
        LogDetails.Clear();
        var upText = eventArgs.Text.ToUpper();

        for (int i = _accounts[accountId.Text!].Logs.Count - 1; i != -1; i--)
        {
            var item = _accounts[accountId.Text!].Logs[i];
            if ((item.Text.Contains(upText)))
                LogDetails.AddItem("[" + item.Date.ToString("hh\\:mm\\:ss") + "] — " + item.Text);
        }
    }

    private void FillList()
    {
        foreach (var (key, value) in _accounts)
        {
            var field = AccountList.AddItem(key);
            field.OnSelected += OnSelectAccount;
        }
        AccountList.SortItemsByText();
    }


}
